### PR TITLE
Fixing encoding errors in FacebookMessenger parser

### PR DESCRIPTION
**Pull request by UntriexTv**
Fix for #73 working on my side.
The reason for invalid encoding was because of non ASCII characters being encoded twice.
[Explanation](https://stackoverflow.com/questions/50008296/facebook-json-badly-encoded)
The code now works without problems and gets rid of all emojis and wrongly encoded characters.
The slovak characters mentioned in the issue are fixed now:
image

### CODE REVIEW

**Comment by joweich** [comment]
@UntriexTv Makes sense! I'm able to connect some dots now: We had a related issue for the Instagram Parser in #65 (see [here](https://github.com/joweich/chat-miner/pull/65#discussion_r1063865767)).
It got resolved by @BlueishTint by going with
```
  "author": mess["sender_name"].encode("latin-1").decode("utf-8"),
  "message": body.encode("latin-1").decode("utf-8")
```
when composing the parsed message into the dict to return.
And this is the _same solution_ like the first proposed resolution in the stackoverflow thread you linked. 
Did you try this approach as well?
I think it's cleaner and has probably better performance since regex matching is quite expensive.

**Comment by UntriexTv** [comment]
@joweich I scraped the regex solution I had in the #73 . It was quick workaround as I had no idea what was happening and GF wanted to try this.
But now I used the solution in the thread I sent and applied it in the loading of json["messages"].
It solved everything (No emoji, no unknown characters and over all seems clean) and also is fast.

**Comment by UntriexTv** [comment]
@joweich Tried with this fix too. Seems to work perfectly

**Comment by joweich** [comment]
@UntriexTv Thank you for your efforts and welcome as a contributor to this project!

**Pull request merged**
