### PR TITLE
Tackle issue in Telegram JSON parser raised in #26

### PR DESCRIPTION
**Pull request by joweich**
It seems like there are different export formats for the JSON exports in telegram.
This PR tackles the issue raised in #26 by @massimopavoni.

### CODE REVIEW

**Comment by massimopavoni** [comment]
Question: is TelegramJsonParser suppose to handle all conversations exported, or a single chat? What about the other supported parsers? 

The `[1]` I had inserted was for a specific chat I wnated to try, so that wouldn't be appropriate for the changes.

**Comment by joweich** [comment]
Alright, I see! I wasn't aware that Telegram can export multiple chats into the same file. This also explains the index and the change in the format.
The other parsers only support one single chat (afaik you can only export one chat at a time on the other platforms).

The parsers will always yield one dataframe for one chat. For me, there are two different solutions:
- Default to the [0] index and throw a warning that all subsequent indices will be ignored
- Give the user the option to choose the index, e.g. via `parser = TelegramJSONParser(FILEPATH, 1)`

What's your opinion @massimopavoni?

**Comment by massimopavoni** [comment]
> Alright, I see! I wasn't aware that Telegram can export multiple chats into the same file. This also explains the index and the change in the format. The other parsers only support one single chat (afaik you can only export one chat at a time on the other platforms).
> 
> The parsers will always yield one dataframe for one chat. For me, there are two different solutions:
> 
>     * Default to the [0] index and throw a warning that all subsequent indices will be ignored
> 
>     * Give the user the option to choose the index, e.g. via `parser = TelegramJSONParser(FILEPATH, 1)`
> 
> 
> What's your opinion @massimopavoni?

I think the best option is to let the user choose which chat to parse, maybe through the name of the chat, filtering the list in the json.

**Comment by joweich** [comment]
> I think the best option is to let the user choose which chat to parse, maybe through the name of the chat, filtering the list in the json.

Calling `parser = TelegramJSONParser(FILEPATH, "chatname")` , then checking if the `chatname` exists in the data  in `TelegramJSONParser_read_file_into_list`, and if it doesn't exist throw an error containing the available names sounds like a robust approach. We would then need to introduce the `__init__` constructor to the `TelegramJSONParser` class.

@massimopavoni do you want to tackle this as you already have the knowledge and data available? I would be very grateful to have you as a contributor in this project!

**Comment by massimopavoni** [comment]
> > I think the best option is to let the user choose which chat to parse, maybe through the name of the chat, filtering the list in the json.
> 
> Calling `parser = TelegramJSONParser(FILEPATH, "chatname")` , then checking if the `chatname` exists in the data in `TelegramJSONParser_read_file_into_list`, and if it doesn't exist throw an error containing the available names sounds like a robust approach. We would then need to introduce the `__init__` constructor to the `TelegramJSONParser` class.
> 
> @massimopavoni do you want to tackle this as you already have the knowledge and data available? I would be very grateful to have you as a contributor in this project!

I will work on it in a couple hours, yes, thank you very much.

**Comment by massimopavoni** [comment]
See #47 too

**Comment by massimopavoni** [comment]
> @massimopavoni welcome to the main branch! blush

@joweich Thank you! It's an honor

**Pull request merged**
